### ISSUE TITLE
Candy machine - where to get/how to build?

### ISSUE THREAD

**Issue by mattdsteele** [ketile/ketile.github.io#1]
I'd love to have one of these on my desk at work, but I can't seem to find the device on any site, and even looking for the Bluetooth Service UUID doesn't turn up much in Google.

Did you build this yourself? Are there any instructions on what to mod to build one?

/cc @tommythorsen, I see your name on [this post](https://groups.google.com/a/chromium.org/forum/#!msg/web-bluetooth/uQP6xIvliwI/XI447_CwEAAJ), which is the only result when I search for the `a6c31337-6c07-453e-961a-d8a8a41bf368` Service ID; anything you can add?

**Comment by tommythorsen** [comment]
Hi Matt!

The two different candy machines that Ketil made were modifications of
these stock toys:

   - https://www.teknikmagasinet.no/produkter/spisbart/godteri/candy-grabber
   -
   https://www.teknikmagasinet.no/produkter/spisbart/godteri/godteriautomat

I'm not really a hardware guy, so I couldn't tell you how to build one for
yourself, though :(

-Tommy

**Comment by ketile** [comment]
Hi Matt,

Thank you for your interest. May I ask where you saw the demo?

The Candy Grabber and Dispenser demos were made in the earlier days of the Web Bluetooth API to showcase the technology to our customers. We worked closely with Google and Opera which is why @tommythorsen shows up using the same custom UUID. I did not create a write-up or tutorial, I'm afraid. 

Both demos use a nRF51 or nRF52 Development Kit and are powered via USB. The Dispenser uses a single relay to turn the motor on or off while the Candy Grabber uses a custom PCB consisting of transistors and relays.

The Candy Grabber is controlled by three DC motors, one for each axis. In addition to turning the motors on and off it is necessary to reverse the direction. You can achieve this by using [DPDT ](http://www.electroschematics.com/9601/dpdt-switch-relay/)relays or by using a regular [relay shield](http://www.dx.com/p/8-channel-5v-relay-module-shield-for-arduino-148811).

I did some changes to the wiring but you might be able to avoid this if you study the signals from the inputs on the Grabber _before_ you tear it apart ;) 

The machine itself is inexpensive and should be readily available. Just do a search for _Candy Grabber_. An alternative to using the nRF5x development kit is to use a [Arduino Primo](http://www.arduino.org/products/boards/arduino-primo). That way you can program in Arduino language and also have the option of connecting the Candy Grabber to the cloud via WiFi.

**Comment by mattdsteele** [comment]
@tommythorsen @ketile thanks for the info!

I can't recall exactly where I first saw the demo (maybe during a presentation on Physical Web/Web Bluetooth at Google IO, or Polymer Summit?), but over the weekend I re-encountered it on the Web Bluetooth Community in G+, as I've been playing with other BT devices via the web: https://plus.google.com/+FrancoisBeaufort/posts/Eg6eRKmdi5h?sfc=true

I'm not much of a hardware person either, but this seems like it'd be a fun project to mess around with. I'll see if there are any folks in my local maker community who might be interested in the project.

Thanks again!
